import { defaults } from "./defaults.js";
import { Serializers } from "./types.js";

export const strategy: Serializers = {
  audio: defaults.audio,
  bookmark: defaults.bookmark,
  breadcrumb: defaults.breadcrumb,
  bulleted_list_item: defaults.bulletedListItem,
  callout: defaults.callout,
  child_database: defaults.childDatabase,
  child_page: defaults.childPage,
  code: defaults.code,
  column: defaults.column,
  column_list: defaults.columnList,
  divider: defaults.divider,
  embed: defaults.embed,
  equation: defaults.equation,
  file: defaults.file,
  heading_1: defaults.heading1,
  heading_2: defaults.heading2,
  heading_3: defaults.heading3,
  image: defaults.image,
  link_preview: defaults.linkPreview,
  link_to_page: defaults.linkToPage,
  numbered_list_item: defaults.numberedListItem,
  paragraph: defaults.paragraph,
  pdf: defaults.pdf,
  quote: defaults.quote,
  synced_block: defaults.syncedBlock,
  table: defaults.table,
  table_of_contents: defaults.tableOfContents,
  table_row: defaults.tableRow,
  template: defaults.template,
  to_do: defaults.toDo,
  toggle: defaults.toggle,
  unsupported: defaults.unsupported,
  video: defaults.video,
};
